version: '3.7'

services:
  backend-server:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: node-server
    container_name: sivr-node-server
    volumes:
    - ./backend/:/usr/src/app
    - /usr/src/app/node_modules
    ports:
      - "8081:8081"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - sivr-network
  
networks:
    sivr-network:
        driver: bridge

volumes:
    node_modules:
    web-root:
      driver: local